#!/bin/sh /etc/rc.common

START=50

USE_PROCD=1

start_instance() {
	local cfg="$1" ifname network args

	config_get ifname $cfg 'ifname'
	config_get network $cfg 'network'

	if [ -n "$network" ]; then
		network_get_device 'ifname' "$network"
	fi

	if [ -z "$ifname" ]; then
		echo "No valid interface or network name."
		exit 1
	fi

	args="$args -i $ifname"

	append_prefix() {
		args="$args -p $1"
	}
	config_list_foreach $cfg prefix append_prefix

	procd_open_instance
	procd_set_param command /usr/sbin/simple-radvd $args
	procd_set_param respawn
	procd_close_instance
}

start_service() {
	config_load simple-radvd
	config_foreach start_instance interface
}
